version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # For Quarkus Maven Plugin, updates are managed by Quarkus Bom dependency
      - dependency-name: io.quarkus:quarkus-maven-plugin