#!/usr/bin/env bash
set -e

# run the tests on JVM
mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify -P $MAVEN_PROFILES -Dts.quarkus.cli.cmd="${HOME}/.jbang/bin/quarkus"

# run the tests on Native
mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify -P $MAVEN_PROFILES -Dnative -Dquarkus.native.container-build=true -Dts.quarkus.cli.cmd="${HOME}/.jbang/bin/quarkus"