
CREATE TABLE airports (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iata_code     VARCHAR(100) NOT NULL UNIQUE,
  city          VARCHAR(100) NOT NULL
);

CREATE TABLE airlines (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iata_code     VARCHAR(100) NOT NULL UNIQUE,
  name          VARCHAR(100) NOT NULL,
  infant_price  FLOAT(7)
);

CREATE TABLE flights (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin        VARCHAR(100) NOT NULL,
  destination   VARCHAR(100) NOT NULL,
  flight_code       VARCHAR(100) NOT NULL,
  base_price    SMALLINT NOT NULL
);

CREATE TABLE pricingRules (
  id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  days_to_departure        SMALLINT NOT NULL,
  until                  SMALLINT NOT NULL,
  percentage             SMALLINT NOT NULL
);

CREATE TABLE address (
  id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  street                 VARCHAR(300) NOT NULL,
  block_number            VARCHAR(20) NOT NULL,
  zip_code                VARCHAR(20) NOT NULL,
  city                   VARCHAR(150) NOT NULL,
  country                VARCHAR(200) NOT NULL,
  created_at             INT NOT NULL,
  updated_at             INT
);

CREATE TABLE passenger (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nif             VARCHAR(15) NOT NULL,
  name            VARCHAR(25) NOT NULL,
  last_name       VARCHAR(55) NOT NULL,
  contact_number  VARCHAR(20) NOT NULL,
  created_at      INT NOT NULL,
  updated_at      INT,
  address_id      NUMBER,
  CONSTRAINT fk_address FOREIGN KEY(address_id) REFERENCES address(id) ON DELETE SET NULL
);

CREATE TABLE basket (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flight          VARCHAR(10) NOT NULL,
  price           NUMERIC NOT NULL,
  created_at      INT NOT NULL,
  updated_at      INT,
  passenger_id    NUMBER,
  CONSTRAINT fk_passenger FOREIGN KEY(passenger_id) REFERENCES passenger(id) ON DELETE SET NULL
);

