quarkus.http.tls-configuration-name=bcfks

quarkus.tls.bcfks.key-store.other.type=BCFKS
quarkus.tls.bcfks.key-store.other.provider=BCFIPS
quarkus.tls.bcfks.key-store.other.path=server-keystore.jks
quarkus.tls.bcfks.key-store.other.alias=localhost
quarkus.tls.bcfks.key-store.credentials-provider.name=custom
quarkus.tls.bcfks.key-store.credentials-provider.bean-name=custom-secret-provider
quarkus.tls.bcfks.key-store.credentials-provider.password-key=key-store-password

quarkus.tls.bcfks.trust-store.other.type=BCFKS
quarkus.tls.bcfks.trust-store.other.provider=BCFIPS
quarkus.tls.bcfks.trust-store.other.path=server-truststore.jks
quarkus.tls.bcfks.trust-store.other.alias=CARoot
quarkus.tls.bcfks.trust-store.credentials-provider.name=custom
quarkus.tls.bcfks.trust-store.credentials-provider.bean-name=custom-secret-provider
quarkus.tls.bcfks.trust-store.credentials-provider.password-key=trust-store-password
