app.name=blockingProducer

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.test.connector=smallrye-kafka
mp.messaging.outgoing.test.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.test.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.test.max.block.ms=1000
mp.messaging.outgoing.test.retries=0
mp.messaging.outgoing.test.compression.type=snappy


# messaging channel for request-reply test
mp.messaging.outgoing.reqrep.connector=smallrye-kafka
mp.messaging.outgoing.reqrep.topic=request
mp.messaging.outgoing.reqrep.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.reqrep.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.reqrep.reply.initial-assignment-timeout=-1

mp.messaging.incoming.request.topic=request
mp.messaging.incoming.request.connector=smallrye-kafka
mp.messaging.incoming.request.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.request.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.reply.connector=smallrye-kafka
#default topic name for replies into "request" topic
mp.messaging.outgoing.reply.topic=request-replies
mp.messaging.outgoing.reply.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.reply.key.serializer=org.apache.kafka.common.serialization.StringSerializer


# channels for request-reply with messages
mp.messaging.outgoing.remessage.connector=smallrye-kafka
mp.messaging.outgoing.remessage.topic=messagerequest
mp.messaging.outgoing.remessage.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.remessage.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.remessage.reply.topic=remess
mp.messaging.outgoing.remessage.reply.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.outgoing.remessage.reply.initial-assignment-timeout=-1

mp.messaging.incoming.inmess.topic=messagerequest
mp.messaging.incoming.inmess.connector=smallrye-kafka
mp.messaging.incoming.inmess.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.inmess.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.outmess.connector=smallrye-kafka
mp.messaging.outgoing.outmess.topic=remess
mp.messaging.outgoing.outmess.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.outmess.key.serializer=org.apache.kafka.common.serialization.StringSerializer