package io.quarkus.ts.vertx.sql.services;

import java.util.List;
import java.util.stream.Collectors;

import io.smallrye.mutiny.Uni;
import io.vertx.core.json.JsonArray;
import io.vertx.mutiny.oracleclient.OracleClient;
import io.vertx.mutiny.sqlclient.Pool;
import io.vertx.mutiny.sqlclient.SqlClientHelper;
import io.vertx.oracleclient.OraclePrepareOptions;
import io.vertx.sqlclient.PropertyKind;

public class DbPoolService extends Pool {

    private final static PropertyKind<Long> LAST_INSERTED_ID = PropertyKind.create("last-inserted-id", Long.class);
    private static final String ORACLE_AUTO_GENERATED_KEY_NAME = "ID";
    private static final OraclePrepareOptions ORACLE_AUTO_GENERATED_KEYS_OPTIONS = new OraclePrepareOptions()
            .setAutoGeneratedKeysIndexes(new JsonArray().add(ORACLE_AUTO_GENERATED_KEY_NAME));
    private final String databaseName;
    private final String selectedDb;

    public DbPoolService(Pool delegate, String dbName, String selectedDb) {
        super(delegate.getDelegate());
        this.databaseName = dbName;
        this.selectedDb = selectedDb;
    }

    public String getTableName(String table) {
        return null == databaseName
                ? table
                : databaseName + "." + table;
    }

    public Uni<Long> save(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        switch (selectedDb) {
            case "mysql":
                return saveMysql(tableName, fieldsNames, fieldsValues);
            case "db2":
                return saveDb2(tableName, fieldsNames, fieldsValues);
            case "mssql":
                return saveMS(tableName, fieldsNames, fieldsValues);
            case "oracle":
                return saveOracle(tableName, fieldsNames, fieldsValues);
            default:
                return savePg(tableName, fieldsNames, fieldsValues);
        }
    }

    private Uni<Long> saveMS(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        return SqlClientHelper.inTransactionUni(this, tx -> {
            String fields = tableFieldsToString(fieldsNames);
            String values = tableFieldsValuesToString(fieldsValues);

            return tx
                    .preparedQuery(
                            "INSERT INTO " + getTableName(tableName) + " (" + fields + ") VALUES (" + values
                                    + "); SELECT SCOPE_IDENTITY() as id;")
                    .execute()
                    .map(r -> r.iterator().next().getLong("id"));
        });
    }

    protected Uni<Long> savePg(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        return SqlClientHelper.inTransactionUni(this, tx -> {
            String fields = tableFieldsToString(fieldsNames);
            String values = tableFieldsValuesToString(fieldsValues);

            return tx
                    .preparedQuery("INSERT INTO " + getTableName(tableName) + " (" + fields + ") VALUES (" + values
                            + ") RETURNING id")
                    .execute().onItem().transform(id -> id.iterator().next().getLong("id"));
        });
    }

    protected Uni<Long> saveMysql(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        return SqlClientHelper.inTransactionUni(this, tx -> {
            String fields = tableFieldsToString(fieldsNames);
            String values = tableFieldsValuesToString(fieldsValues);

            return tx
                    .preparedQuery(
                            "INSERT INTO " + getTableName(tableName) + " (" + fields + ") VALUES (" + values + ")")
                    .execute()
                    .onItem().invoke(r -> this.query("SELECT LAST_INSERT_ID();"))
                    .onItem().transform(id -> (Long) id.getDelegate().property(LAST_INSERTED_ID));
        });
    }

    protected Uni<Long> saveDb2(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        return SqlClientHelper.inTransactionUni(this, tx -> {
            String fields = tableFieldsToString(fieldsNames);
            String values = tableFieldsValuesToString(fieldsValues);

            return tx
                    .preparedQuery("select id from NEW TABLE (INSERT INTO " + getTableName(tableName) + " ("
                            + fields + ") VALUES (" + values + "))")
                    .execute().onItem().transform(id -> id.iterator().next().getLong("id"));
        });
    }

    protected Uni<Long> saveOracle(String tableName, List<String> fieldsNames, List<Object> fieldsValues) {
        return SqlClientHelper.inTransactionUni(this, tx -> {
            String fields = tableFieldsToString(fieldsNames);
            String values = tableFieldsValuesToString(fieldsValues);

            return tx
                    .preparedQuery("INSERT INTO " + getTableName(tableName) + " (" + fields + ") VALUES (" + values + ")",
                            ORACLE_AUTO_GENERATED_KEYS_OPTIONS)
                    .execute()
                    .onItem()
                    .transform(rows -> rows.property(OracleClient.GENERATED_KEYS).getLong(ORACLE_AUTO_GENERATED_KEY_NAME));
        });
    }

    private String tableFieldsToString(List<String> fieldsNames) {
        return String.join(",", fieldsNames);
    }

    private String tableFieldsValuesToString(List<Object> fieldsValues) {
        return fieldsValues.stream()
                .map(n -> {
                    String content = String.valueOf(n);
                    if (n instanceof String) {
                        return "'" + n + "'";
                    }

                    return content;
                }).collect(Collectors.joining(",", "", ""));
    }
}
