quarkus.langchain4j.openai.api-key=REPLACE_ME

%debug.quarkus.mcp.server.traffic-logging.enabled=true
%debug.quarkus.mcp.server.traffic-logging.text-limit=1000

%openai.quarkus.langchain4j.openai.chat-model.temperature=0
# we use mini here, since smaller models are unable to hold the context from the system message
%openai.quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
%openai.quarkus.langchain4j.openai.log-requests=true

%named.quarkus.langchain4j.openai.custom.chat-model.temperature=0
%named.quarkus.langchain4j.openai.custom.chat-model.model-name=gpt-4.1-nano
%named.quarkus.langchain4j.openai.custom.log-requests=true
