quarkus.tls.server.key-store.p12.path=server-keystore.p12
quarkus.tls.server.key-store.p12.password=password

quarkus.tls.server.trust-store.p12.path=server-truststore.p12
quarkus.tls.server.trust-store.p12.password=password

quarkus.http.tls-configuration-name=server
quarkus.http.ssl.client-auth=required

#required for the OpenShift app to start
quarkus.http.insecure-requests=enabled 

quarkus.native.additional-build-args=-H:IncludeResources=.*\\.p12