quarkus.oidc.absolute-redirect.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.absolute-redirect.client-id=test-application-client
quarkus.oidc.absolute-redirect.application-type=web-app
quarkus.oidc.absolute-redirect.credentials.secret=test-application-client-secret
quarkus.oidc.absolute-redirect.tls.tls-configuration-name=${quarkus.oidc.tls.tls-configuration-name}
quarkus.oidc.absolute-redirect.roles.source=accesstoken
quarkus.oidc.absolute-redirect.authentication.redirect-path=/absolute-redirect/callback
quarkus.oidc.absolute-redirect.tenant-paths=/absolute-redirect,/absolute-redirect/callback

quarkus.oidc.restore-path-absolute-redirect.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.restore-path-absolute-redirect.client-id=test-application-client
quarkus.oidc.restore-path-absolute-redirect.application-type=web-app
quarkus.oidc.restore-path-absolute-redirect.credentials.secret=test-application-client-secret
quarkus.oidc.restore-path-absolute-redirect.tls.tls-configuration-name=${quarkus.oidc.tls.tls-configuration-name}
quarkus.oidc.restore-path-absolute-redirect.roles.source=accesstoken
quarkus.oidc.restore-path-absolute-redirect.authentication.redirect-path=/absolute-redirect/restore-callback
quarkus.oidc.restore-path-absolute-redirect.authentication.restore-path-after-redirect=true
quarkus.oidc.restore-path-absolute-redirect.tenant-paths=/absolute-redirect/restore-path,/absolute-redirect/restore-callback
