%debug.quarkus.mcp.server.traffic-logging.enabled=true
%debug.quarkus.mcp.server.traffic-logging.text-limit=1000
quarkus.mcp.server.tools.page-size=2
working.folder=target/classes/
# otherwise we run into problems while parsing CLI logs on Windows
quarkus.console.color=false

# This config is based on recommendations from https://docs.quarkiverse.io/quarkus-mcp-server/dev/guides-oidc.html
# lines below are copied verbatim, their description in upstream is sufficient
%oidc.quarkus.oidc.resource-metadata.enabled=true
%oidc.quarkus.oidc.resource-metadata.scopes=admin
# keycloak puts user roles into 'realm_access' claim of access token, in a JSON like this: {"roles":["test-admin-role","uma_protection","test-user-role"]}
# line below is used to retrieve the roles
%oidc.quarkus.oidc.roles.role-claim-path=realm_access/roles
# below we define a policy, pick paths which it affects and roles from keycloak realm, which receive access
%oidc.quarkus.http.auth.permission.mcp-endpoints.policy=admin-scope-required
%oidc.quarkus.http.auth.policy.admin-scope-required.roles-allowed=test-admin-role
%oidc.quarkus.http.auth.permission.mcp-endpoints.paths=/mcp/*
%oidc.quarkus.oidc.token.lifespan-grace=5