name: 'Create Quarkus CLI 999-SNAPSHOT'
description: 'Creates Quarkus CLI based on the current Quarkus main (999-SNAPSHOT version)'
runs:
  using: "composite"
  steps:
    - name: Install Quarkus CLI
      shell: bash
      run: |
        cat <<EOF > ./quarkus-dev-cli
        #!/bin/bash
        java -jar ~/.m2/repository/io/quarkus/quarkus-cli/999-SNAPSHOT/quarkus-cli-999-SNAPSHOT-runner.jar "\$@"
        EOF
        chmod +x ./quarkus-dev-cli
        ./quarkus-dev-cli version

