CREATE TABLE AUTHORS(ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME NVARCHAR2(20) NOT NULL);
INSERT INTO authors(id,name) VALUES (1, 'Homer');
INSERT INTO authors(id,name) VALUES (2, 'Vern');
INSERT INTO authors(id,name) VALUES (3, 'Dlugi');
INSERT INTO authors(id,name) VALUES (4, 'Kahneman');
-- We do not do any checks for any of the three tables below, but have to create them or the validation will complain
CREATE TABLE books(id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, author INT references authors(id) , title VARCHAR(500) NOT NULL, isbn VARCHAR(50));
CREATE TABLE person(id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(30) NOT NULL);
CREATE TABLE XmlValidatedCustomer(id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(30) NOT NULL,  email VARCHAR(30) NOT NULL);
create sequence XmlValidatedCustomer_SEQ start with 1 increment by 50;
