<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.quarkus.ts.qe</groupId>
    <version>1.0.0-SNAPSHOT</version>
    <artifactId>sbom-cyclonedx</artifactId>
    <name>Quarkus QE TS: SBOM CycloneDx</name>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.quarkus.qe</groupId>
                <artifactId>quarkus-test-parent</artifactId>
                <version>${quarkus.qe.framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <scope>test</scope>
                <version>${assertj.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <properties>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.release>17</maven.compiler.release>
        <gitflow-incremental-builder.version>4.7.0</gitflow-incremental-builder.version>
        <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <compiler-plugin.version>3.16.0</compiler-plugin.version>
        <surefire-plugin.version>3.6.0</surefire-plugin.version>
        <failsafe-plugin.version>3.6.0</failsafe-plugin.version>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>999-core-3.39-SNAPSHOT</quarkus.platform.version>
        <quarkus.ide.version>3.30.0</quarkus.ide.version>
        <quarkus.qe.framework.version>999-SNAPSHOT</quarkus.qe.framework.version>
        <quarkus-qpid-jms.version>2.14.0</quarkus-qpid-jms.version>
        <confluent.kafka-avro-serializer.version>7.5.1</confluent.kafka-avro-serializer.version>
        <formatter-maven-plugin.version>2.29.0</formatter-maven-plugin.version>
        <impsort-maven-plugin.version>1.13.0</impsort-maven-plugin.version>
        <xml-format-maven-plugin.version>4.1.0</xml-format-maven-plugin.version>
        <checkstyle.version>12.1.2</checkstyle.version>
        <jsoup.version>1.23.2</jsoup.version>
        <quarkiverse.config.version>2.5.0</quarkiverse.config.version>
        <quarkiverse.pact.version>1.6.1</quarkiverse.pact.version>
        <assertj.version>3.27.7</assertj.version>
        <htmlunit.version>5.5.0</htmlunit.version>
        <java.websocket.version>1.6.0</java.websocket.version>
        <mcp-sdk.version>2.0.1</mcp-sdk.version>
        <!-- Faster build when using -DskipTests -->
        <quarkus.build.skip>${skipTests}</quarkus.build.skip>
        <!-- S2i configuration -->
        <quarkus.s2i.base-jvm-image>registry.access.redhat.com/ubi9/openjdk-21:latest</quarkus.s2i.base-jvm-image>
        <quarkus.s2i.base-native-image>quay.io/quarkus/ubi9-quarkus-native-binary-s2i:2.0</quarkus.s2i.base-native-image>
        <!-- Default values for format -->
        <src.format.goal>format</src.format.goal>
        <src.sort.goal>sort</src.sort.goal>
        <xml.format.goal>xml-format</xml.format.goal>
        <!-- Failsafe inclusions/exclusions rules -->
        <include.tests>**/*IT.java</include.tests>
        <exclude.openshift.tests>**/OpenShift*IT.java</exclude.openshift.tests>
        <exclude.serverless.openshift.tests>**/Serverless*OpenShift*IT.java</exclude.serverless.openshift.tests>
        <exclude.operator.openshift.tests>**/Operator*OpenShift*IT.java</exclude.operator.openshift.tests>
        <exclude.quarkus.cli.tests>**/QuarkusCli*IT.java</exclude.quarkus.cli.tests>
        <exclude.quarkus.devmode.tests>no</exclude.quarkus.devmode.tests>
        <!-- Docker images used by both surefire and failsafe plugin -->
        <postgresql.latest.image>docker.io/library/postgres:18</postgresql.latest.image>
        <postgis.latest.image>docker.io/postgis/postgis:18-3.6</postgis.latest.image>
        <!-- The upstream MySQL version is needed for DevMode as the RH image is not starting with Quarkus-->
        <mysql.upstream.image>docker.io/library/mysql:9.7</mysql.upstream.image>
        <mysql.image>${mysql.upstream.image}</mysql.image>
        <rhbk.image>registry.redhat.io/rhbk/keycloak-rhel9:26.6</rhbk.image>
        <wiremock.version>3.13.2</wiremock.version>
        <build-reporter-maven-extension.version>3.13.1</build-reporter-maven-extension.version>
        <reruns>2</reruns>
        <oc.reruns>1</oc.reruns>
        <flaky-run-reporter.version>0.1.7</flaky-run-reporter.version>
        <repository.update.policy>daily</repository.update.policy>
    </properties>
    <build>
        <extensions>
            <!-- Build Reporter collects and generates build reports analyzed by Jenkins jobs using AWS EC2 Windows-->
            <extension>
                <groupId>io.quarkus.bot</groupId>
                <artifactId>build-reporter-maven-extension</artifactId>
                <version>${build-reporter-maven-extension.version}</version>
            </extension>
            <!--Creates report about detected flaky tests during SureFire and FailSafe test runs -->
            <extension>
                <groupId>io.quarkus.qe</groupId>
                <artifactId>flaky-run-reporter</artifactId>
                <version>${flaky-run-reporter.version}</version>
            </extension>
        </extensions>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <configuration>
                        <rerunFailingTestsCount>${reruns}</rerunFailingTestsCount>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${failsafe-plugin.version}</version>
                    <configuration>
                        <!-- fixes unavailable native binary build logs, https://github.com/quarkus-qe/quarkus-test-framework/issues/785 -->
                        <forkNode implementation="org.apache.maven.plugin.surefire.extensions.SurefireForkNodeFactory"/>
                        <rerunFailingTestsCount>${reruns}</rerunFailingTestsCount>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>io.quarkus.qe</groupId>
                <artifactId>quarkus-test-preparer</artifactId>
                <version>${quarkus.qe.framework.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-pom-mojo</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>build</id>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <annotationProcessorPathsUseDepMgmt>true</annotationProcessorPathsUseDepMgmt>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <!-- Services used in test suite -->
                        <postgresql.latest.image>${postgresql.latest.image}</postgresql.latest.image>
                        <postgis.latest.image>${postgis.latest.image}</postgis.latest.image>
                        <mysql.upstream.image>${mysql.upstream.image}</mysql.upstream.image>
                        <mysql.image>${mysql.image}</mysql.image>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>${include.tests}</include>
                            </includes>
                            <excludes>
                                <exclude>${exclude.openshift.tests}</exclude>
                                <exclude>${exclude.serverless.openshift.tests}</exclude>
                                <exclude>${exclude.operator.openshift.tests}</exclude>
                                <exclude>${exclude.quarkus.cli.tests}</exclude>
                                <exclude>${exclude.quarkus.devmode.tests}</exclude>
                            </excludes>
                            <systemPropertyVariables>
                                <!-- S2i configuration for OpenShift -->
                                <quarkus.s2i.base-jvm-image>${quarkus.s2i.base-jvm-image}</quarkus.s2i.base-jvm-image>
                                <quarkus.s2i.base-native-image>${quarkus.s2i.base-native-image}</quarkus.s2i.base-native-image>
                                <!-- Services used in test suite -->
                                <nginx.image>docker.io/library/nginx:1-alpine</nginx.image>
                                <!-- Keep amq broker as it is as the newer ones are only available through registry.redhat.io
                                 which is behind credentials -->
                                <amqbroker.image>registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:latest</amqbroker.image>
                                <amqbroker.1.0x.image>quay.io/arkmq-org/arkmq-org-broker:artemis.2.55.0</amqbroker.1.0x.image>
                                <redpanda.image>redpandadata/redpanda:v26.1.12</redpanda.image>
                                <postgresql.latest.image>${postgresql.latest.image}</postgresql.latest.image>
                                <postgis.latest.image>${postgis.latest.image}</postgis.latest.image>
                                <elastic.9x.image>docker.io/library/elasticsearch:9.4.1</elastic.9x.image>
                                <mysql.upstream.image>${mysql.upstream.image}</mysql.upstream.image>
                                <mysql.image>${mysql.image}</mysql.image>
                                <mariadb.12.image>docker.io/library/mariadb:12.3-ubi10</mariadb.12.image>
                                <mssql.image>mcr.microsoft.com/mssql/rhel/server:2025-latest</mssql.image>
                                <!-- Oracle image - we aim to use same version as Dev Services for Oracle so that we only download one image -->
                                <oracle.image>docker.io/gvenzl/oracle-free:23-slim-faststart</oracle.image>
                                <db2.image>icr.io/db2_community/db2:12.1.0.0</db2.image>
                                <mongodb.image>docker.io/library/mongo:8.3</mongodb.image>
                                <redis.image>docker.io/library/redis:8</redis.image>
                                <wiremock.image>docker.io/wiremock/wiremock:3x</wiremock.image>
                                <!-- We're not allowed to use newer consul version than 1.16.4 due to changed license -->
                                <consul.image>docker.io/hashicorp/consul:1.16.4</consul.image>
                                <infinispan.image>quay.io/infinispan/server:16.0</infinispan.image>
                                <infinispan.expected-log>Infinispan Server.*started in</infinispan.expected-log>
                                <spring.cloud.server.image>quay.io/quarkusqeteam/spring-cloud-config-server:4.1</spring.cloud.server.image>
                                <keycloak.image>quay.io/keycloak/keycloak:26.7</keycloak.image>
                                <bouncycastle.bctls-fips.version>1.0.12.2</bouncycastle.bctls-fips.version>
                                <rhbk.image>${rhbk.image}</rhbk.image>
                                <quarkus.platform.group-id>${quarkus.platform.group-id}</quarkus.platform.group-id>
                                <quarkus.platform.version>${quarkus.platform.version}</quarkus.platform.version>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <version>${formatter-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>${src.format.goal}</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <artifactId>quarkus-ide-config</artifactId>
                        <groupId>io.quarkus</groupId>
                        <version>${quarkus.ide.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <configFile>eclipse-format.xml</configFile>
                    <lineEnding>LF</lineEnding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <version>${impsort-maven-plugin.version}</version>
                <configuration>
                    <!-- store outside of target to speed up formatting when mvn clean is used -->
                    <cachedir>.cache</cachedir>
                    <groups>java.,jakarta.,org.,com.,io.</groups>
                    <staticGroups>*</staticGroups>
                    <removeUnused>true</removeUnused>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>${src.sort.goal}</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>au.com.acegi</groupId>
                <artifactId>xml-format-maven-plugin</artifactId>
                <version>${xml-format-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>${xml.format.goal}</goal>
                        </goals>
                        <configuration>
                            <indentSize>4</indentSize>
                            <excludes>
                                <!-- Exclude files from target folder -->
                                <exclude>**/target/**/*.xml</exclude>
                                <!-- Exclude Quarkus main repository -->
                                <exclude>**/quarkus/**/*.xml</exclude>
                                <!-- Exclude .idea -->
                                <exclude>.idea/**</exclude>
                                <!-- Exclude .github -->
                                <exclude>.github/**</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <configuration>
                    <configLocation>checkstyle.xml</configLocation>
                    <!-- To exclude autogenerated sources -->
                    <sourceDirectories>${project.build.sourceDirectory}</sourceDirectories>
                    <consoleOutput>true</consoleOutput>
                    <failsOnError>true</failsOnError>
                    <linkXRef>true</linkXRef>
                    <includeTestSourceDirectory>true</includeTestSourceDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>${checkstyle.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                        <quarkus.native.enabled>${quarkus.native.enabled}</quarkus.native.enabled>
                                        <quarkus.native.container-build>${quarkus.native.container-build}</quarkus.native.container-build>
                                        <quarkus.native.native-image-xmx>${quarkus.native.native-image-xmx}</quarkus.native.native-image-xmx>
                                        <quarkus.native.builder-image>${quarkus.native.builder-image}</quarkus.native.builder-image>
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.native.enabled>true</quarkus.native.enabled>
                <quarkus.native.container-build>true</quarkus.native.container-build>
                <quarkus.native.native-image-xmx>6g</quarkus.native.native-image-xmx>
                <quarkus.native.builder-image>quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25</quarkus.native.builder-image>
                <exclude.quarkus.devmode.tests>**/*DevMode*IT.java</exclude.quarkus.devmode.tests>
            </properties>
        </profile>
    </profiles>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-cyclonedx</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-quartz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-qute</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-core-java</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus.qe</groupId>
            <artifactId>quarkus-test-containers</artifactId>
            <version>${quarkus.qe.framework.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
